### ISSUE TITLE
Acer-A715-BIOS

### ISSUE THREAD

**Issue by WangGang-a1** [WangGang-a1/Acer-A715-EFI#2]
宏碁的BIOS是h20的BIOS，目前只能通过硬刷的方式来解锁CFG，解锁CFG便可以成功驱动原生电源管理

**Comment by VeTsgG** [comment]
能指导一下怎么硬刷BIOS吗

**Comment by WangGang-a1** [comment]
需要硬刷的，去哔哩哔哩找个硬刷bios教程就行，然后自己去百度个改好的bios

**Comment by VeTsgG** [comment]
百度搜不到A715改好的的BIOS啊 是用UEFITool自己改吗  还有你说的找客服要工程版BIOS靠谱吗

**Comment by WangGang-a1** [comment]
自己改也可以，官方那个你得要好久（我是这样）

**Comment by karlkam** [comment]
> 自己改也可以，官方那個你得要好久（我是這樣）

可以分享一下a715 bios 文件吗， 多谢
