### ISSUE TITLE
NVMe SSD

### ISSUE THREAD

**Issue by MagicianLjj** [WangGang-a1/Acer-A715-EFI#3]
安装时，磁盘工具找不到硬盘  系数sn520 和 550

**Comment by WangGang-a1** [comment]
可以去b站搜索黑果小白观看我的视频，可以直接安装，是原版系统制作的https://b23.tv/IYzopY

**Comment by WangGang-a1** [comment]
> 安装时，磁盘工具找不到硬盘 系数sn520 和 550

更换nvme补丁或者驱动试试
