### ISSUE TITLE
希望添加个配套能用的安装教程

### ISSUE THREAD

**Issue by ylmf56** [WangGang-a1/Acer-A715-EFI#9]
打开进入EFI发现并没有install OS选项。。。 

希望大佬添加上成功安装所使用的教程链接，不然我等小白根本不会用

**Comment by WangGang-a1** [comment]
> 

最近在准备考试啦，还有结课论文，会考虑出的，安一下空格就出来隐藏选项啦，我把那些繁杂的选项隐藏了

**Comment by WangGang-a1** [comment]
请前往我的博客查看blog.qltxy.cn
